package com.bozo.springbootecommerce.bootsrap;

import com.bozo.springbootecommerce.dao.ProductCategoryRepository;
import com.bozo.springbootecommerce.dao.ProductRepository;
import com.bozo.springbootecommerce.entity.Product;
import com.bozo.springbootecommerce.entity.ProductCategory;
import lombok.AllArgsConstructor;
import org.springframework.boot.CommandLineRunner;
import org.springframework.stereotype.Component;

import java.math.BigDecimal;
import java.util.Date;

@Component
@AllArgsConstructor
public class DataLoader implements CommandLineRunner {

    private ProductRepository productRepository;
    private ProductCategoryRepository productCategoryRepository;
    @Override
    public void run(String... args) throws Exception {

//        books
        ProductCategory books = productCategoryRepository.save(ProductCategory.builder().categoryName("Books").build());

        productRepository.save(Product.builder()
                .sku("BOOK-TECH-1000")
                .name("Crash Course in Python")
                .description("Learn Python at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!")
                .imageUrl("assets/images/products/books/book-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("14.99"))
                .dateCreated(new Date())
                .category(books)
                .build());

        productRepository.save(Product.builder()
                .sku("BOOK-TECH-1001")
                .name("Become a Guru in JavaScript")
                .description("Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!")
                .imageUrl("assets/images/products/books/book-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("20.99"))
                .dateCreated(new Date())
                .category(books)
                .build());

        productRepository.save(Product.builder()
                .sku("BOOK-TECH-1002")
                .name("Exploring Vue.js")
                .description("Learn Vue.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!")
                .imageUrl("assets/images/products/books/book-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("14.99"))
                .dateCreated(new Date())
                .category(books)
                .build());

        productRepository.save(Product.builder()
                .sku("BOOK-TECH-1000")
                .name("Crash Course in Python")
                .description("Learn Python at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!")
                .imageUrl("assets/images/products/books/book-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("14.99"))
                .dateCreated(new Date())
                .category(books)
                .build());

        productRepository.save(Product.builder()
                .sku("BOOK-TECH-1001")
                .name("Become a Guru in JavaScript")
                .description("Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!")
                .imageUrl("assets/images/products/books/book-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("20.99"))
                .dateCreated(new Date())
                .category(books)
                .build());

        productRepository.save(Product.builder()
                .sku("BOOK-TECH-1002")
                .name("Exploring Vue.js")
                .description("Learn Vue.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!")
                .imageUrl("assets/images/products/books/book-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("14.99"))
                .dateCreated(new Date())
                .category(books)
                .build());

        productRepository.save(Product.builder()
                .sku("BOOK-TECH-1000")
                .name("Crash Course in Python")
                .description("Learn Python at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!")
                .imageUrl("assets/images/products/books/book-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("14.99"))
                .dateCreated(new Date())
                .category(books)
                .build());

        productRepository.save(Product.builder()
                .sku("BOOK-TECH-1001")
                .name("Become a Guru in JavaScript")
                .description("Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!")
                .imageUrl("assets/images/products/books/book-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("20.99"))
                .dateCreated(new Date())
                .category(books)
                .build());

        productRepository.save(Product.builder()
                .sku("BOOK-TECH-1002")
                .name("Exploring Vue.js")
                .description("Learn Vue.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!")
                .imageUrl("assets/images/products/books/book-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("14.99"))
                .dateCreated(new Date())
                .category(books)
                .build());

        productRepository.save(Product.builder()
                .sku("BOOK-TECH-1000")
                .name("Crash Course in Python")
                .description("Learn Python at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!")
                .imageUrl("assets/images/products/books/book-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("14.99"))
                .dateCreated(new Date())
                .category(books)
                .build());

        productRepository.save(Product.builder()
                .sku("BOOK-TECH-1001")
                .name("Become a Guru in JavaScript")
                .description("Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!")
                .imageUrl("assets/images/products/books/book-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("20.99"))
                .dateCreated(new Date())
                .category(books)
                .build());

        productRepository.save(Product.builder()
                .sku("BOOK-TECH-1002")
                .name("Exploring Vue.js")
                .description("Learn Vue.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!")
                .imageUrl("assets/images/products/books/book-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("14.99"))
                .dateCreated(new Date())
                .category(books)
                .build());

        productRepository.save(Product.builder()
                .sku("BOOK-TECH-1000")
                .name("Crash Course in Python")
                .description("Learn Python at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!")
                .imageUrl("assets/images/products/books/book-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("14.99"))
                .dateCreated(new Date())
                .category(books)
                .build());

        productRepository.save(Product.builder()
                .sku("BOOK-TECH-1001")
                .name("Become a Guru in JavaScript")
                .description("Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!")
                .imageUrl("assets/images/products/books/book-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("20.99"))
                .dateCreated(new Date())
                .category(books)
                .build());

        productRepository.save(Product.builder()
                .sku("BOOK-TECH-1002")
                .name("Exploring Vue.js")
                .description("Learn Vue.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!")
                .imageUrl("assets/images/products/books/book-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("14.99"))
                .dateCreated(new Date())
                .category(books)
                .build());

        productRepository.save(Product.builder()
                .sku("BOOK-TECH-1000")
                .name("Crash Course in Python")
                .description("Learn Python at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!")
                .imageUrl("assets/images/products/books/book-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("14.99"))
                .dateCreated(new Date())
                .category(books)
                .build());

        productRepository.save(Product.builder()
                .sku("BOOK-TECH-1001")
                .name("Become a Guru in JavaScript")
                .description("Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!")
                .imageUrl("assets/images/products/books/book-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("20.99"))
                .dateCreated(new Date())
                .category(books)
                .build());

        productRepository.save(Product.builder()
                .sku("BOOK-TECH-1002")
                .name("Exploring Vue.js")
                .description("Learn Vue.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!")
                .imageUrl("assets/images/products/books/book-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("14.99"))
                .dateCreated(new Date())
                .category(books)
                .build());

        productRepository.save(Product.builder()
                .sku("BOOK-TECH-1000")
                .name("Crash Course in Python")
                .description("Learn Python at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!")
                .imageUrl("assets/images/products/books/book-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("14.99"))
                .dateCreated(new Date())
                .category(books)
                .build());

        productRepository.save(Product.builder()
                .sku("BOOK-TECH-1001")
                .name("Become a Guru in JavaScript")
                .description("Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!")
                .imageUrl("assets/images/products/books/book-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("20.99"))
                .dateCreated(new Date())
                .category(books)
                .build());

        productRepository.save(Product.builder()
                .sku("BOOK-TECH-1002")
                .name("Exploring Vue.js")
                .description("Learn Vue.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!")
                .imageUrl("assets/images/products/books/book-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("14.99"))
                .dateCreated(new Date())
                .category(books)
                .build());

        productRepository.save(Product.builder()
                .sku("BOOK-TECH-1000")
                .name("Crash Course in Python")
                .description("Learn Python at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!")
                .imageUrl("assets/images/products/books/book-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("14.99"))
                .dateCreated(new Date())
                .category(books)
                .build());

        productRepository.save(Product.builder()
                .sku("BOOK-TECH-1001")
                .name("Become a Guru in JavaScript")
                .description("Learn JavaScript at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!")
                .imageUrl("assets/images/products/books/book-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("20.99"))
                .dateCreated(new Date())
                .category(books)
                .build());

        productRepository.save(Product.builder()
                .sku("BOOK-TECH-1002")
                .name("Exploring Vue.js")
                .description("Learn Vue.js at your own pace. The author explains how the technology works in easy-to-understand language. This book includes working examples that you can apply to your own projects. Purchase the book and get started today!")
                .imageUrl("assets/images/products/books/book-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("14.99"))
                .dateCreated(new Date())
                .category(books)
                .build());


//        coffee mugs
        ProductCategory coffeeMugs = productCategoryRepository.save(ProductCategory.builder().categoryName("Coffee Mugs").build());

        productRepository.save(Product.builder()
                .sku("COFFEEMUG-1000")
                .name("Coffee Mug - Express")
                .description("Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!")
                .imageUrl("assets/images/products/coffeemugs/coffeemug-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("18.99"))
                .dateCreated(new Date())
                .category(coffeeMugs)
                .build());

        productRepository.save(Product.builder()
                .sku("COFFEEMUG-1001")
                .name("Coffee Mug - Cherokee")
                .description("Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!")
                .imageUrl("assets/images/products/coffeemugs/coffeemug-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("18.99"))
                .dateCreated(new Date())
                .category(coffeeMugs)
                .build());

        productRepository.save(Product.builder()
                .sku("COFFEEMUG-1002")
                .name("Coffee Mug - Sweeper")
                .description("Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!")
                .imageUrl("assets/images/products/coffeemugs/coffeemug-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("18.99"))
                .dateCreated(new Date())
                .category(coffeeMugs)
                .build());

        productRepository.save(Product.builder()
                .sku("COFFEEMUG-1000")
                .name("Coffee Mug - Express")
                .description("Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!")
                .imageUrl("assets/images/products/coffeemugs/coffeemug-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("18.99"))
                .dateCreated(new Date())
                .category(coffeeMugs)
                .build());

        productRepository.save(Product.builder()
                .sku("COFFEEMUG-1001")
                .name("Coffee Mug - Cherokee")
                .description("Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!")
                .imageUrl("assets/images/products/coffeemugs/coffeemug-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("18.99"))
                .dateCreated(new Date())
                .category(coffeeMugs)
                .build());

        productRepository.save(Product.builder()
                .sku("COFFEEMUG-1002")
                .name("Coffee Mug - Sweeper")
                .description("Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!")
                .imageUrl("assets/images/products/coffeemugs/coffeemug-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("18.99"))
                .dateCreated(new Date())
                .category(coffeeMugs)
                .build());

        productRepository.save(Product.builder()
                .sku("COFFEEMUG-1000")
                .name("Coffee Mug - Express")
                .description("Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!")
                .imageUrl("assets/images/products/coffeemugs/coffeemug-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("18.99"))
                .dateCreated(new Date())
                .category(coffeeMugs)
                .build());

        productRepository.save(Product.builder()
                .sku("COFFEEMUG-1001")
                .name("Coffee Mug - Cherokee")
                .description("Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!")
                .imageUrl("assets/images/products/coffeemugs/coffeemug-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("18.99"))
                .dateCreated(new Date())
                .category(coffeeMugs)
                .build());

        productRepository.save(Product.builder()
                .sku("COFFEEMUG-1002")
                .name("Coffee Mug - Sweeper")
                .description("Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!")
                .imageUrl("assets/images/products/coffeemugs/coffeemug-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("18.99"))
                .dateCreated(new Date())
                .category(coffeeMugs)
                .build());

        productRepository.save(Product.builder()
                .sku("COFFEEMUG-1000")
                .name("Coffee Mug - Express")
                .description("Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!")
                .imageUrl("assets/images/products/coffeemugs/coffeemug-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("18.99"))
                .dateCreated(new Date())
                .category(coffeeMugs)
                .build());

        productRepository.save(Product.builder()
                .sku("COFFEEMUG-1001")
                .name("Coffee Mug - Cherokee")
                .description("Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!")
                .imageUrl("assets/images/products/coffeemugs/coffeemug-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("18.99"))
                .dateCreated(new Date())
                .category(coffeeMugs)
                .build());

        productRepository.save(Product.builder()
                .sku("COFFEEMUG-1002")
                .name("Coffee Mug - Sweeper")
                .description("Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!")
                .imageUrl("assets/images/products/coffeemugs/coffeemug-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("18.99"))
                .dateCreated(new Date())
                .category(coffeeMugs)
                .build());

        productRepository.save(Product.builder()
                .sku("COFFEEMUG-1000")
                .name("Coffee Mug - Express")
                .description("Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!")
                .imageUrl("assets/images/products/coffeemugs/coffeemug-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("18.99"))
                .dateCreated(new Date())
                .category(coffeeMugs)
                .build());

        productRepository.save(Product.builder()
                .sku("COFFEEMUG-1001")
                .name("Coffee Mug - Cherokee")
                .description("Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!")
                .imageUrl("assets/images/products/coffeemugs/coffeemug-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("18.99"))
                .dateCreated(new Date())
                .category(coffeeMugs)
                .build());

        productRepository.save(Product.builder()
                .sku("COFFEEMUG-1002")
                .name("Coffee Mug - Sweeper")
                .description("Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!")
                .imageUrl("assets/images/products/coffeemugs/coffeemug-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("18.99"))
                .dateCreated(new Date())
                .category(coffeeMugs)
                .build());

        productRepository.save(Product.builder()
                .sku("COFFEEMUG-1000")
                .name("Coffee Mug - Express")
                .description("Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!")
                .imageUrl("assets/images/products/coffeemugs/coffeemug-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("18.99"))
                .dateCreated(new Date())
                .category(coffeeMugs)
                .build());

        productRepository.save(Product.builder()
                .sku("COFFEEMUG-1001")
                .name("Coffee Mug - Cherokee")
                .description("Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!")
                .imageUrl("assets/images/products/coffeemugs/coffeemug-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("18.99"))
                .dateCreated(new Date())
                .category(coffeeMugs)
                .build());

        productRepository.save(Product.builder()
                .sku("COFFEEMUG-1002")
                .name("Coffee Mug - Sweeper")
                .description("Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!")
                .imageUrl("assets/images/products/coffeemugs/coffeemug-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("18.99"))
                .dateCreated(new Date())
                .category(coffeeMugs)
                .build());

        productRepository.save(Product.builder()
                .sku("COFFEEMUG-1000")
                .name("Coffee Mug - Express")
                .description("Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!")
                .imageUrl("assets/images/products/coffeemugs/coffeemug-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("18.99"))
                .dateCreated(new Date())
                .category(coffeeMugs)
                .build());

        productRepository.save(Product.builder()
                .sku("COFFEEMUG-1001")
                .name("Coffee Mug - Cherokee")
                .description("Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!")
                .imageUrl("assets/images/products/coffeemugs/coffeemug-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("18.99"))
                .dateCreated(new Date())
                .category(coffeeMugs)
                .build());

        productRepository.save(Product.builder()
                .sku("COFFEEMUG-1002")
                .name("Coffee Mug - Sweeper")
                .description("Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!")
                .imageUrl("assets/images/products/coffeemugs/coffeemug-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("18.99"))
                .dateCreated(new Date())
                .category(coffeeMugs)
                .build());

        productRepository.save(Product.builder()
                .sku("COFFEEMUG-1000")
                .name("Coffee Mug - Express")
                .description("Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!")
                .imageUrl("assets/images/products/coffeemugs/coffeemug-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("18.99"))
                .dateCreated(new Date())
                .category(coffeeMugs)
                .build());

        productRepository.save(Product.builder()
                .sku("COFFEEMUG-1001")
                .name("Coffee Mug - Cherokee")
                .description("Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!")
                .imageUrl("assets/images/products/coffeemugs/coffeemug-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("18.99"))
                .dateCreated(new Date())
                .category(coffeeMugs)
                .build());

        productRepository.save(Product.builder()
                .sku("COFFEEMUG-1002")
                .name("Coffee Mug - Sweeper")
                .description("Do you love mathematics? If so, then you need this elegant coffee mug with an amazing fractal design. You don\\'t have to worry about boring coffee mugs anymore. This coffee mug will be the topic of conversation in the office, guaranteed! Buy it now!")
                .imageUrl("assets/images/products/coffeemugs/coffeemug-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("18.99"))
                .dateCreated(new Date())
                .category(coffeeMugs)
                .build());


//        mouse pads
        ProductCategory mousePads = productCategoryRepository.save(ProductCategory.builder().categoryName("Mouse Pads").build());

        productRepository.save(Product.builder()
                .sku("MOUSEPAD-1000")
                .name("Mouse Pad - Express")
                .description("Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!")
                .imageUrl("assets/images/products/mousepads/mousepad-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("17.99"))
                .dateCreated(new Date())
                .category(mousePads)
                .build());

        productRepository.save(Product.builder()
                .sku("MOUSEPAD-1001")
                .name("Mouse Pad - Cherokee")
                .description("Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!")
                .imageUrl("assets/images/products/mousepads/mousepad-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("17.99"))
                .dateCreated(new Date())
                .category(mousePads)
                .build());

        productRepository.save(Product.builder()
                .sku("MOUSEPAD-1002")
                .name("Mouse Pad - Sweeper")
                .description("Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!")
                .imageUrl("assets/images/products/mousepads/mousepad-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("17.99"))
                .dateCreated(new Date())
                .category(mousePads)
                .build());

        productRepository.save(Product.builder()
                .sku("MOUSEPAD-1000")
                .name("Mouse Pad - Express")
                .description("Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!")
                .imageUrl("assets/images/products/mousepads/mousepad-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("17.99"))
                .dateCreated(new Date())
                .category(mousePads)
                .build());

        productRepository.save(Product.builder()
                .sku("MOUSEPAD-1001")
                .name("Mouse Pad - Cherokee")
                .description("Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!")
                .imageUrl("assets/images/products/mousepads/mousepad-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("17.99"))
                .dateCreated(new Date())
                .category(mousePads)
                .build());

        productRepository.save(Product.builder()
                .sku("MOUSEPAD-1002")
                .name("Mouse Pad - Sweeper")
                .description("Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!")
                .imageUrl("assets/images/products/mousepads/mousepad-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("17.99"))
                .dateCreated(new Date())
                .category(mousePads)
                .build());

        productRepository.save(Product.builder()
                .sku("MOUSEPAD-1000")
                .name("Mouse Pad - Express")
                .description("Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!")
                .imageUrl("assets/images/products/mousepads/mousepad-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("17.99"))
                .dateCreated(new Date())
                .category(mousePads)
                .build());

        productRepository.save(Product.builder()
                .sku("MOUSEPAD-1001")
                .name("Mouse Pad - Cherokee")
                .description("Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!")
                .imageUrl("assets/images/products/mousepads/mousepad-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("17.99"))
                .dateCreated(new Date())
                .category(mousePads)
                .build());

        productRepository.save(Product.builder()
                .sku("MOUSEPAD-1002")
                .name("Mouse Pad - Sweeper")
                .description("Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!")
                .imageUrl("assets/images/products/mousepads/mousepad-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("17.99"))
                .dateCreated(new Date())
                .category(mousePads)
                .build());

        productRepository.save(Product.builder()
                .sku("MOUSEPAD-1000")
                .name("Mouse Pad - Express")
                .description("Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!")
                .imageUrl("assets/images/products/mousepads/mousepad-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("17.99"))
                .dateCreated(new Date())
                .category(mousePads)
                .build());

        productRepository.save(Product.builder()
                .sku("MOUSEPAD-1001")
                .name("Mouse Pad - Cherokee")
                .description("Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!")
                .imageUrl("assets/images/products/mousepads/mousepad-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("17.99"))
                .dateCreated(new Date())
                .category(mousePads)
                .build());

        productRepository.save(Product.builder()
                .sku("MOUSEPAD-1002")
                .name("Mouse Pad - Sweeper")
                .description("Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!")
                .imageUrl("assets/images/products/mousepads/mousepad-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("17.99"))
                .dateCreated(new Date())
                .category(mousePads)
                .build());

        productRepository.save(Product.builder()
                .sku("MOUSEPAD-1000")
                .name("Mouse Pad - Express")
                .description("Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!")
                .imageUrl("assets/images/products/mousepads/mousepad-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("17.99"))
                .dateCreated(new Date())
                .category(mousePads)
                .build());

        productRepository.save(Product.builder()
                .sku("MOUSEPAD-1001")
                .name("Mouse Pad - Cherokee")
                .description("Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!")
                .imageUrl("assets/images/products/mousepads/mousepad-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("17.99"))
                .dateCreated(new Date())
                .category(mousePads)
                .build());

        productRepository.save(Product.builder()
                .sku("MOUSEPAD-1002")
                .name("Mouse Pad - Sweeper")
                .description("Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!")
                .imageUrl("assets/images/products/mousepads/mousepad-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("17.99"))
                .dateCreated(new Date())
                .category(mousePads)
                .build());

        productRepository.save(Product.builder()
                .sku("MOUSEPAD-1000")
                .name("Mouse Pad - Express")
                .description("Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!")
                .imageUrl("assets/images/products/mousepads/mousepad-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("17.99"))
                .dateCreated(new Date())
                .category(mousePads)
                .build());

        productRepository.save(Product.builder()
                .sku("MOUSEPAD-1001")
                .name("Mouse Pad - Cherokee")
                .description("Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!")
                .imageUrl("assets/images/products/mousepads/mousepad-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("17.99"))
                .dateCreated(new Date())
                .category(mousePads)
                .build());

        productRepository.save(Product.builder()
                .sku("MOUSEPAD-1002")
                .name("Mouse Pad - Sweeper")
                .description("Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!")
                .imageUrl("assets/images/products/mousepads/mousepad-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("17.99"))
                .dateCreated(new Date())
                .category(mousePads)
                .build());

        productRepository.save(Product.builder()
                .sku("MOUSEPAD-1000")
                .name("Mouse Pad - Express")
                .description("Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!")
                .imageUrl("assets/images/products/mousepads/mousepad-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("17.99"))
                .dateCreated(new Date())
                .category(mousePads)
                .build());

        productRepository.save(Product.builder()
                .sku("MOUSEPAD-1001")
                .name("Mouse Pad - Cherokee")
                .description("Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!")
                .imageUrl("assets/images/products/mousepads/mousepad-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("17.99"))
                .dateCreated(new Date())
                .category(mousePads)
                .build());

        productRepository.save(Product.builder()
                .sku("MOUSEPAD-1002")
                .name("Mouse Pad - Sweeper")
                .description("Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!")
                .imageUrl("assets/images/products/mousepads/mousepad-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("17.99"))
                .dateCreated(new Date())
                .category(mousePads)
                .build());

        productRepository.save(Product.builder()
                .sku("MOUSEPAD-1000")
                .name("Mouse Pad - Express")
                .description("Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!")
                .imageUrl("assets/images/products/mousepads/mousepad-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("17.99"))
                .dateCreated(new Date())
                .category(mousePads)
                .build());

        productRepository.save(Product.builder()
                .sku("MOUSEPAD-1001")
                .name("Mouse Pad - Cherokee")
                .description("Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!")
                .imageUrl("assets/images/products/mousepads/mousepad-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("17.99"))
                .dateCreated(new Date())
                .category(mousePads)
                .build());

        productRepository.save(Product.builder()
                .sku("MOUSEPAD-1002")
                .name("Mouse Pad - Sweeper")
                .description("Fractal images are amazing! You can now own a mouse pad with a unique and amazing fractal. The mouse pad is made of a durable and smooth material. Your mouse will easily glide across the mouse pad. This mouse pad will brighten your workspace. Buy it now!")
                .imageUrl("assets/images/products/mousepads/mousepad-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("17.99"))
                .dateCreated(new Date())
                .category(mousePads)
                .build());


//        luggage tags
        ProductCategory luggageTags = productCategoryRepository.save(ProductCategory.builder().categoryName("Luggage Tags").build());

        productRepository.save(Product.builder()
                .sku("LUGGAGETAG-1000")
                .name("Luggage Tag - Cherish")
                .description("This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!")
                .imageUrl("assets/images/products/luggagetags/luggagetag-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("16.99"))
                .dateCreated(new Date())
                .category(luggageTags)
                .build());

        productRepository.save(Product.builder()
                .sku("LUGGAGETAG-1001")
                .name("Luggage Tag - Adventure")
                .description("This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!")
                .imageUrl("assets/images/products/luggagetags/luggagetag-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("16.99"))
                .dateCreated(new Date())
                .category(luggageTags)
                .build());

        productRepository.save(Product.builder()
                .sku("LUGGAGETAG-1002")
                .name("Luggage Tag - Skyline")
                .description("This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!")
                .imageUrl("assets/images/products/luggagetags/luggagetag-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("16.99"))
                .dateCreated(new Date())
                .category(luggageTags)
                .build());

        productRepository.save(Product.builder()
                .sku("LUGGAGETAG-1000")
                .name("Luggage Tag - Cherish")
                .description("This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!")
                .imageUrl("assets/images/products/luggagetags/luggagetag-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("16.99"))
                .dateCreated(new Date())
                .category(luggageTags)
                .build());

        productRepository.save(Product.builder()
                .sku("LUGGAGETAG-1001")
                .name("Luggage Tag - Adventure")
                .description("This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!")
                .imageUrl("assets/images/products/luggagetags/luggagetag-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("16.99"))
                .dateCreated(new Date())
                .category(luggageTags)
                .build());

        productRepository.save(Product.builder()
                .sku("LUGGAGETAG-1002")
                .name("Luggage Tag - Skyline")
                .description("This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!")
                .imageUrl("assets/images/products/luggagetags/luggagetag-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("16.99"))
                .dateCreated(new Date())
                .category(luggageTags)
                .build());

        productRepository.save(Product.builder()
                .sku("LUGGAGETAG-1000")
                .name("Luggage Tag - Cherish")
                .description("This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!")
                .imageUrl("assets/images/products/luggagetags/luggagetag-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("16.99"))
                .dateCreated(new Date())
                .category(luggageTags)
                .build());

        productRepository.save(Product.builder()
                .sku("LUGGAGETAG-1001")
                .name("Luggage Tag - Adventure")
                .description("This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!")
                .imageUrl("assets/images/products/luggagetags/luggagetag-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("16.99"))
                .dateCreated(new Date())
                .category(luggageTags)
                .build());

        productRepository.save(Product.builder()
                .sku("LUGGAGETAG-1002")
                .name("Luggage Tag - Skyline")
                .description("This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!")
                .imageUrl("assets/images/products/luggagetags/luggagetag-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("16.99"))
                .dateCreated(new Date())
                .category(luggageTags)
                .build());

        productRepository.save(Product.builder()
                .sku("LUGGAGETAG-1000")
                .name("Luggage Tag - Cherish")
                .description("This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!")
                .imageUrl("assets/images/products/luggagetags/luggagetag-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("16.99"))
                .dateCreated(new Date())
                .category(luggageTags)
                .build());

        productRepository.save(Product.builder()
                .sku("LUGGAGETAG-1001")
                .name("Luggage Tag - Adventure")
                .description("This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!")
                .imageUrl("assets/images/products/luggagetags/luggagetag-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("16.99"))
                .dateCreated(new Date())
                .category(luggageTags)
                .build());

        productRepository.save(Product.builder()
                .sku("LUGGAGETAG-1002")
                .name("Luggage Tag - Skyline")
                .description("This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!")
                .imageUrl("assets/images/products/luggagetags/luggagetag-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("16.99"))
                .dateCreated(new Date())
                .category(luggageTags)
                .build());

        productRepository.save(Product.builder()
                .sku("LUGGAGETAG-1000")
                .name("Luggage Tag - Cherish")
                .description("This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!")
                .imageUrl("assets/images/products/luggagetags/luggagetag-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("16.99"))
                .dateCreated(new Date())
                .category(luggageTags)
                .build());

        productRepository.save(Product.builder()
                .sku("LUGGAGETAG-1001")
                .name("Luggage Tag - Adventure")
                .description("This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!")
                .imageUrl("assets/images/products/luggagetags/luggagetag-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("16.99"))
                .dateCreated(new Date())
                .category(luggageTags)
                .build());

        productRepository.save(Product.builder()
                .sku("LUGGAGETAG-1002")
                .name("Luggage Tag - Skyline")
                .description("This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!")
                .imageUrl("assets/images/products/luggagetags/luggagetag-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("16.99"))
                .dateCreated(new Date())
                .category(luggageTags)
                .build());

        productRepository.save(Product.builder()
                .sku("LUGGAGETAG-1000")
                .name("Luggage Tag - Cherish")
                .description("This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!")
                .imageUrl("assets/images/products/luggagetags/luggagetag-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("16.99"))
                .dateCreated(new Date())
                .category(luggageTags)
                .build());

        productRepository.save(Product.builder()
                .sku("LUGGAGETAG-1001")
                .name("Luggage Tag - Adventure")
                .description("This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!")
                .imageUrl("assets/images/products/luggagetags/luggagetag-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("16.99"))
                .dateCreated(new Date())
                .category(luggageTags)
                .build());

        productRepository.save(Product.builder()
                .sku("LUGGAGETAG-1002")
                .name("Luggage Tag - Skyline")
                .description("This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!")
                .imageUrl("assets/images/products/luggagetags/luggagetag-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("16.99"))
                .dateCreated(new Date())
                .category(luggageTags)
                .build());

        productRepository.save(Product.builder()
                .sku("LUGGAGETAG-1000")
                .name("Luggage Tag - Cherish")
                .description("This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!")
                .imageUrl("assets/images/products/luggagetags/luggagetag-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("16.99"))
                .dateCreated(new Date())
                .category(luggageTags)
                .build());

        productRepository.save(Product.builder()
                .sku("LUGGAGETAG-1001")
                .name("Luggage Tag - Adventure")
                .description("This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!")
                .imageUrl("assets/images/products/luggagetags/luggagetag-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("16.99"))
                .dateCreated(new Date())
                .category(luggageTags)
                .build());

        productRepository.save(Product.builder()
                .sku("LUGGAGETAG-1002")
                .name("Luggage Tag - Skyline")
                .description("This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!")
                .imageUrl("assets/images/products/luggagetags/luggagetag-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("16.99"))
                .dateCreated(new Date())
                .category(luggageTags)
                .build());

        productRepository.save(Product.builder()
                .sku("LUGGAGETAG-1000")
                .name("Luggage Tag - Cherish")
                .description("This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!")
                .imageUrl("assets/images/products/luggagetags/luggagetag-luv2code-1000.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("16.99"))
                .dateCreated(new Date())
                .category(luggageTags)
                .build());

        productRepository.save(Product.builder()
                .sku("LUGGAGETAG-1001")
                .name("Luggage Tag - Adventure")
                .description("This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!")
                .imageUrl("assets/images/products/luggagetags/luggagetag-luv2code-1001.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("16.99"))
                .dateCreated(new Date())
                .category(luggageTags)
                .build());

        productRepository.save(Product.builder()
                .sku("LUGGAGETAG-1002")
                .name("Luggage Tag - Skyline")
                .description("This luggage tag will help you identify your luggage. The luggage tag is very unique and it will stand out from the crowd. The luggage tag is created out of a rugged and durable plastic. Buy this luggage tag now to make it easy to identify your luggage!")
                .imageUrl("assets/images/products/luggagetags/luggagetag-luv2code-1002.png")
                .active(true)
                .unitsInStock(100)
                .unitPrice(new BigDecimal("16.99"))
                .dateCreated(new Date())
                .category(luggageTags)
                .build());

    }
}
